!function(){/*

 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
"undefined"!==typeof window&&(window.PR_SHOULD_USE_CONTINUATION=!0);
(function(){function W(d){function c(a){var n=a.charCodeAt(0);if(92!==n)return n;var f=a.charAt(1);return(n=y[f])?n:"0"<=f&&"7">=f?parseInt(a.substring(1),8):"u"===f||"x"===f?parseInt(a.substring(2),16):a.charCodeAt(1)}function g(a){if(32>a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);return"\\"===a||"-"===a||"]"===a||"^"===a?"\\"+a:a}function l(a){var n=(new RegExpCompat("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"))[Symbol.match](a.substring(1,
a.length-1));a=[];var f="^"===n[0],h=["["];f&&h.push("^");f=f?1:0;for(var e=n.length;f<e;++f){var b=n[f];if((new RegExpCompat("\\\\[bdsw]","i")).test(b))h.push(b);else{b=c(b);if(f+2<e&&"-"===n[f+1]){var k=c(n[f+2]);f+=2}else k=b;a.push([b,k]);65>k||122<b||(65>k||90<b||a.push([Math.max(65,b)|32,Math.min(k,90)|32]),97>k||122<b||a.push([Math.max(97,b)&-33,Math.min(k,122)&-33]))}}a.sort(function(r,u){return r[0]-u[0]||u[1]-r[1]});n=[];e=[];for(f=0;f<a.length;++f)b=a[f],b[0]<=e[1]+1?e[1]=Math.max(e[1],
b[1]):n.push(e=b);for(f=0;f<n.length;++f)b=n[f],h.push(g(b[0])),b[1]>b[0]&&(b[1]+1>b[0]&&h.push("-"),h.push(g(b[1])));h.push("]");return h.join("")}function v(a){for(var n=(new RegExpCompat("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g"))[Symbol.match](a.source),f=n.length,h=[],e=0,b=0;e<f;++e){var k=n[e];"("===k?++b:"\\"===k.charAt(0)&&(k=+k.substring(1))&&(k<=b?h[k]=-1:n[e]=g(k))}for(e=
1;e<h.length;++e)-1===h[e]&&(h[e]=++B);for(b=e=0;e<f;++e)k=n[e],"("===k?(++b,h[b]||(n[e]="(?:")):"\\"===k.charAt(0)&&(k=+k.substring(1))&&k<=b&&(n[e]="\\"+h[k]);for(e=0;e<f;++e)"^"===n[e]&&"^"!==n[e+1]&&(n[e]="");if(a.ignoreCase&&w)for(e=0;e<f;++e)k=n[e],a=k.charAt(0),2<=k.length&&"["===a?n[e]=l(k):"\\"!==a&&(n[e]=(new RegExpCompat("[a-zA-Z]","g"))[Symbol.replace](k,function(r){r=r.charCodeAt(0);return"["+String.fromCharCode(r&-33,r|32)+"]"}));return n.join("")}for(var B=0,w=!1,t=!1,q=0,m=d.length;q<
m;++q){var p=d[q];if(p.ignoreCase)t=!0;else if((new RegExpCompat("[a-z]","i")).test((new RegExpCompat("\\\\u[0-9a-f]{4}|\\\\x[0-9a-f]{2}|\\\\[^ux]","gi"))[Symbol.replace](p.source,""))){w=!0;t=!1;break}}var y={b:8,t:9,n:10,v:11,f:12,r:13},x=[];q=0;for(m=d.length;q<m;++q){p=d[q];if(p.global||p.multiline)throw Error(""+p);x.push("(?:"+v(p)+")")}return new RegExpCompat(x.join("|"),t?"gi":"g")}function X(d,c){function g(q){var m=q.nodeType;if(1==m){if(!l.test(q.className)){for(m=q.firstChild;m;m=m.nextSibling)g(m);
m=q.nodeName.toLowerCase();if("br"===m||"li"===m)v[t]="\n",w[t<<1]=B++,w[t++<<1|1]=q}}else if(3==m||4==m)m=q.nodeValue,m.length&&(m=c?(new RegExpCompat("\\r\\n?","g"))[Symbol.replace](m,"\n"):(new RegExpCompat("[ \\t\\r\\n]+","g"))[Symbol.replace](m," "),v[t]=m,w[t<<1]=B,B+=m.length,w[t++<<1|1]=q)}var l=new RegExpCompat("(?:^|\\s)nocode(?:\\s|$)"),v=[],B=0,w=[],t=0;g(d);return{g:(new RegExpCompat("\\n$"))[Symbol.replace](v.join(""),""),h:w}}function M(d,c,g,l,v){g&&(d={j:d,o:1,m:null,s:null,g,h:null,
l:c,i:null},l(d),v.push.apply(v,d.i))}function Y(d){for(var c=void 0,g=d.firstChild;g;g=g.nextSibling){var l=g.nodeType;c=1===l?c?d:g:3===l?Z.test(g.nodeValue)?d:c:c}return c===d?void 0:c}function H(d,c){function g(w){for(var t=w.l,q=w.j,m=[t,"pln"],p=0,y=v[Symbol.match](w.g)||[],x={},a=0,n=y.length;a<n;++a){var f=y[a],h=x[f],e=void 0;if("string"===typeof h)var b=!1;else{var k=l[f.charAt(0)];if(k)e=k[1][Symbol.match](f),h=k[0];else{for(b=0;b<B;++b)if(k=c[b],e=k[1][Symbol.match](f)){h=k[0];break}e||
(h="pln")}!(b=5<=h.length&&"lang-"===h.substring(0,5))||e&&"string"===typeof e[1]||(b=!1,h="src");b||(x[f]=h)}k=p;p+=f.length;if(b){b=e[1];var r=f.indexOf(b),u=r+b.length;e[2]&&(u=f.length-e[2].length,r=u-b.length);h=h.substring(5);M(q,t+k,f.substring(0,r),g,m);M(q,t+k+r,b,O(h,b),m);M(q,t+k+u,f.substring(u),g,m)}else m.push(t+k,h)}w.i=m}var l={},v;(function(){for(var w=d.concat(c),t=[],q={},m=0,p=w.length;m<p;++m){var y=w[m],x=y[3];if(x)for(var a=x.length;0<=--a;)l[x.charAt(a)]=y;y=y[1];x=""+y;q.hasOwnProperty(x)||
(t.push(y),q[x]=null)}t.push(new RegExpCompat("[\x00-\uffff]"));v=W(t)})();var B=c.length;return g}function D(d){var c=[],g=[];d.tripleQuotedStrings?c.push(["str",new RegExpCompat("^(?:\\'\\'\\'(?:[^\\'\\\\]|\\\\[\\s\\S]|\\'{1,2}(?=[^\\']))*(?:\\'\\'\\'|$)|\\\"\\\"\\\"(?:[^\\\"\\\\]|\\\\[\\s\\S]|\\\"{1,2}(?=[^\\\"]))*(?:\\\"\\\"\\\"|$)|\\'(?:[^\\\\\\']|\\\\[\\s\\S])*(?:\\'|$)|\\\"(?:[^\\\\\\\"]|\\\\[\\s\\S])*(?:\\\"|$))"),null,"'\""]):d.multiLineStrings?c.push(["str",new RegExpCompat("^(?:\\'(?:[^\\\\\\']|\\\\[\\s\\S])*(?:\\'|$)|\\\"(?:[^\\\\\\\"]|\\\\[\\s\\S])*(?:\\\"|$)|\\`(?:[^\\\\\\`]|\\\\[\\s\\S])*(?:\\`|$))"),
null,"'\"`"]):c.push(["str",new RegExpCompat("^(?:\\'(?:[^\\\\\\'\\r\\n]|\\\\.)*(?:\\'|$)|\\\"(?:[^\\\\\\\"\\r\\n]|\\\\.)*(?:\\\"|$))"),null,"\"'"]);d.verbatimStrings&&g.push(["str",new RegExpCompat('^@\\"(?:[^\\"]|\\"\\")*(?:\\"|$)'),null]);var l=d.hashComments;l&&(d.cStyleComments?(1<l?c.push(["com",new RegExpCompat("^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)"),null,"#"]):c.push(["com",new RegExpCompat("^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\\b|[^\\r\\n]*)"),
null,"#"]),g.push(["str",new RegExpCompat("^<(?:(?:(?:\\.\\.\\/)*|\\/?)(?:[\\w-]+(?:\\/[\\w-]+)+)?[\\w-]+\\.h(?:h|pp|\\+\\+)?|[a-z]\\w*)>"),null])):c.push(["com",new RegExpCompat("^#[^\\r\\n]*"),null,"#"]));d.cStyleComments&&(g.push(["com",new RegExpCompat("^\\/\\/[^\\r\\n]*"),null]),g.push(["com",new RegExpCompat("^\\/\\*[\\s\\S]*?(?:\\*\\/|$)"),null]));if(l=d.regexLiterals){var v=(l=1<l?"":"\n\r")?".":"[\\S\\s]";g.push(["lang-regex",new RegExpCompat("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*"+
(l+"])(?:[^/\\x5B\\x5C"+l+"]|\\x5C"+v+"|\\x5B(?:[^\\x5C\\x5D"+l+"]|\\x5C"+v+")*(?:\\x5D|$))+/)"))])}(l=d.types)&&g.push(["typ",l]);l=(new RegExpCompat("^ | $","g"))[Symbol.replace](""+d.keywords,"");l.length&&g.push(["kwd",new RegExpCompat("^(?:"+(new RegExpCompat("[\\s,]+","g"))[Symbol.replace](l,"|")+")\\b"),null]);c.push(["pln",new RegExpCompat("^\\s+"),null," \r\n\t\u00a0"]);l="^.[^\\s\\w.$@'\"`/\\\\]*";d.regexLiterals&&(l+="(?!s*/)");g.push(["lit",new RegExpCompat("^@[a-z_$][a-z_$@0-9]*","i"),
null],["typ",new RegExpCompat("^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\\w+_t\\b)"),null],["pln",new RegExpCompat("^[a-z_$][a-z_$@0-9]*","i"),null],["lit",new RegExpCompat("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pln",new RegExpCompat("^\\\\[\\s\\S]?"),null],["pun",new RegExpCompat(l),null]);return H(c,g)}function P(d,c,g){function l(a){var n=a.nodeType;if(1==n&&!B.test(a.className))if("br"===a.nodeName.toLowerCase())v(a),a.parentNode&&
a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)l(a);else if((3==n||4==n)&&g){var f=a.nodeValue,h=w[Symbol.match](f);h&&(n=f.substring(0,h.index),a.nodeValue=n,(f=f.substring(h.index+h[0].length))&&a.parentNode.insertBefore(t.createTextNode(f),a.nextSibling),v(a),n||a.parentNode.removeChild(a))}}function v(a){function n(h,e){e=e?h.cloneNode(!1):h;var b=h.parentNode;if(b){b=n(b,1);h=h.nextSibling;b.appendChild(e);for(var k=h;k;k=h)h=k.nextSibling,b.appendChild(k)}return e}for(;!a.nextSibling;)if(a=
a.parentNode,!a)return;a=n(a.nextSibling,0);for(var f;(f=a.parentNode)&&1===f.nodeType;)a=f;m.push(a)}for(var B=new RegExpCompat("(?:^|\\s)nocode(?:\\s|$)"),w=new RegExpCompat("\\r\\n?|\\n"),t=d.ownerDocument,q=t.createElement("li");d.firstChild;)q.appendChild(d.firstChild);for(var m=[q],p=0;p<m.length;++p)l(m[p]);c===(c|0)&&m[0].setAttribute("value",c);var y=t.createElement("ol");y.className="linenums";c=Math.max(0,c-1|0)||0;p=0;for(var x=m.length;p<x;++p)q=m[p],q.className="L"+(p+c)%10,q.firstChild||
q.appendChild(t.createTextNode("\u00a0")),y.appendChild(q);d.appendChild(y)}function C(d,c){for(var g=c.length;0<=--g;){var l=c[g];K.hasOwnProperty(l)?E.console&&console.warn("cannot override language handler %s",l):K[l]=d}}function O(d,c){d&&K.hasOwnProperty(d)||(d=(new RegExpCompat("^\\s*<")).test(c)?"default-markup":"default-code");return K[d]}function Q(d){var c=d.m;try{var g=X(d.j,d.o),l=g.g;d.g=l;d.h=g.h;d.l=0;O(c,l)(d);var v=(new RegExpCompat("\\bMSIE\\s(\\d+)")).exec(navigator.userAgent);
v=v&&8>=+v[1];var B=new RegExpCompat("\n","g"),w=d.g,t=w.length;c=0;var q=d.h,m=q.length;g=0;var p=d.i,y=p.length;l=0;p[y]=t;var x,a;for(a=x=0;a<y;)p[a]!==p[a+2]?(p[x++]=p[a++],p[x++]=p[a++]):a+=2;y=x;for(a=x=0;a<y;){for(var n=p[a],f=p[a+1],h=a+2;h+2<=y&&p[h+1]===f;)h+=2;p[x++]=n;p[x++]=f;a=h}p.length=x;var e=d.j;d="";e&&(d=e.style.display,e.style.display="none");try{for(;g<m;){var b=q[g+2]||t,k=p[l+2]||t;h=Math.min(b,k);var r=q[g+1],u;if(1!==r.nodeType&&(u=w.substring(c,h))){v&&(u=B[Symbol.replace](u,
"\r"));r.nodeValue=u;var z=r.ownerDocument,A=z.createElement("span");A.className=p[l+1];var I=r.parentNode;I.replaceChild(A,r);A.appendChild(r);c<b&&(q[g+1]=r=z.createTextNode(w.substring(h,b)),I.insertBefore(r,A.nextSibling))}c=h;c>=b&&(g+=2);c>=k&&(l+=2)}}finally{e&&(e.style.display=d)}}catch(L){E.console&&console.log(L&&L.stack||L)}}var E="undefined"!==typeof window?window:{},F=["break,continue,do,else,for,if,return,while"],G=[[F,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,restrict,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],
"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],J=[G,"alignas,alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,noexcept,noreturn,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],R=[G,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],
S=[G,"abstract,add,alias,as,ascending,async,await,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,get,global,group,implicit,in,interface,internal,into,is,join,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,remove,sbyte,sealed,select,set,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,value,var,virtual,where,yield"];G=[G,"abstract,async,await,constructor,debugger,enum,eval,export,from,function,get,import,implements,instanceof,interface,let,null,of,set,undefined,var,with,yield,Infinity,NaN"];
var T=[F,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],U=[F,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"];F=[F,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"];var N=[J,S,R,G,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",
T,U,F],V=new RegExpCompat("^(DIR|FILE|array|vector|(de|priority_)?queue|(forward_)?list|stack|(const_)?(reverse_)?iterator|(unordered_)?(multi)?(set|map)|bitset|u?(int|float)\\d*)\\b"),Z=new RegExpCompat("\\S");N=D({keywords:N,hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0});var K={};C(N,["default-code"]);C(H([],[["pln",new RegExpCompat("^[^<?]+")],["dec",new RegExpCompat("^<!\\w[^>]*(?:>|$)")],["com",new RegExpCompat("^<\\!--[\\s\\S]*?(?:-\\->|$)")],["lang-",new RegExpCompat("^<\\?([\\s\\S]+?)(?:\\?>|$)")],
["lang-",new RegExpCompat("^<%([\\s\\S]+?)(?:%>|$)")],["pun",new RegExpCompat("^(?:<[%?]|[%?]>)")],["lang-",new RegExpCompat("^<xmp\\b[^>]*>([\\s\\S]+?)<\\/xmp\\b[^>]*>","i")],["lang-js",new RegExpCompat("^<script\\b[^>]*>([\\s\\S]*?)(<\\/script\\b[^>]*>)","i")],["lang-css",new RegExpCompat("^<style\\b[^>]*>([\\s\\S]*?)(<\\/style\\b[^>]*>)","i")],["lang-in.tag",new RegExpCompat("^(<\\/?[a-z][^<>]*>)","i")]]),"default-markup htm html mxml xhtml xml xsl".split(" "));C(H([["pln",new RegExpCompat("^[\\s]+"),
null," \t\r\n"],["atv",new RegExpCompat("^(?:\\\"[^\\\"]*\\\"?|\\'[^\\']*\\'?)"),null,"\"'"]],[["tag",new RegExpCompat("^^<\\/?[a-z](?:[\\w.:-]*\\w)?|\\/?>$","i")],["atn",new RegExpCompat("^(?!style[\\s=]|on)[a-z](?:[\\w:-]*\\w)?","i")],["lang-uq.val",new RegExpCompat("^=\\s*([^>\\'\\\"\\s]*(?:[^>\\'\\\"\\s\\/]|\\/(?=\\s)))")],["pun",new RegExpCompat("^[=<>\\/]+")],["lang-js",new RegExpCompat('^on\\w+\\s*=\\s*\\"([^\\"]+)\\"',"i")],["lang-js",new RegExpCompat("^on\\w+\\s*=\\s*\\'([^\\']+)\\'","i")],
["lang-js",new RegExpCompat("^on\\w+\\s*=\\s*([^\\\"\\'>\\s]+)","i")],["lang-css",new RegExpCompat('^style\\s*=\\s*\\"([^\\"]+)\\"',"i")],["lang-css",new RegExpCompat("^style\\s*=\\s*\\'([^\\']+)\\'","i")],["lang-css",new RegExpCompat("^style\\s*=\\s*([^\\\"\\'>\\s]+)","i")]]),["in.tag"]);C(H([],[["atv",new RegExpCompat("^[\\s\\S]+")]]),["uq.val"]);C(D({keywords:J,hashComments:!0,cStyleComments:!0,types:V}),"c cc cpp cxx cyc m".split(" "));C(D({keywords:"null,true,false"}),["json"]);C(D({keywords:S,
hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:V}),["cs"]);C(D({keywords:R,cStyleComments:!0}),["java"]);C(D({keywords:F,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);C(D({keywords:T,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);C(D({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,
multiLineStrings:!0,regexLiterals:2}),["perl","pl","pm"]);C(D({keywords:U,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);C(D({keywords:G,cStyleComments:!0,regexLiterals:!0}),["javascript","js","ts","typescript"]);C(D({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),
["coffee"]);C(H([],[["str",new RegExpCompat("^[\\s\\S]+")]]),["regex"]);var ca=E.PR={createSimpleLexer:H,registerLangHandler:C,sourceDecorator:D,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:E.prettyPrintOne=function(d,c,g){g=g||!1;c=c||null;var l=document.createElement("div");l.innerHTML="<pre>"+d+"</pre>";
l=l.firstChild;g&&P(l,g,!0);Q({m:c,s:g,j:l,o:1,g:null,l:null,h:null,i:null});return l.innerHTML},prettyPrint:E.prettyPrint=function(d,c){function g(){for(var e=E.PR_SHOULD_USE_CONTINUATION?q.now()+250:Infinity;m<v.length&&q.now()<e;m++){for(var b=v[m],k=h,r=b;r=r.previousSibling;){var u=r.nodeType,z=(7===u||8===u)&&r.nodeValue;if(z?!(new RegExpCompat("^\\??prettify\\b")).test(z):3!==u||(new RegExpCompat("\\S")).test(r.nodeValue))break;if(z){k={};(new RegExpCompat("\\b(\\w+)=([\\w:.%+-]+)","g"))[Symbol.replace](z,
function(L,aa,ba){k[aa]=ba});break}}r=b.className;if((k!==h||y.test(r))&&!x.test(r)){u=!1;for(z=b.parentNode;z;z=z.parentNode){var A=z.tagName;if(A&&f.test(A)&&z.className&&y.test(z.className)){u=!0;break}}if(!u){b.className+=" prettyprinted";u=k.lang;if(!u){u=r.match(p);var I;!u&&(I=Y(b))&&n.test(I.tagName)&&(u=p[Symbol.match](I.className));u&&=u[1]}a.test(b.tagName)?z=1:(z=b.currentStyle,A=l.defaultView,z=(z=z?z.whiteSpace:A&&A.getComputedStyle?A.getComputedStyle(b,null).getPropertyValue("white-space"):
0)&&"pre"===z.substring(0,3));A=k.linenums;(A="true"===A||+A)||(A=(A=(new RegExpCompat("\\blinenums\\b(?::(\\d+))?"))[Symbol.match](r))?A[1]&&A[1].length?+A[1]:!0:!1);A&&P(b,A,z);Q({m:u,j:b,s:A,o:z,g:null,l:null,h:null,i:null})}}}m<v.length?E.setTimeout(g,250):"function"===typeof d&&d()}c=c||document.body;var l=c.ownerDocument||document;c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")];for(var v=[],B=0;B<c.length;++B)for(var w=0,t=c[B].length;w<t;++w)v.push(c[B][w]);
c=null;var q=Date;q.now||(q={now:function(){return+new Date}});var m=0,p=new RegExpCompat("\\blang(?:uage)?-([\\w.]+)(?!\\S)"),y=new RegExpCompat("\\bprettyprint\\b"),x=new RegExpCompat("\\bprettyprinted\\b"),a=new RegExpCompat("pre|xmp","i"),n=new RegExpCompat("^code$","i"),f=new RegExpCompat("^(?:pre|code|xmp)$","i"),h={};g()}};J=E.define;"function"===typeof J&&J.amd&&J("google-code-prettify",[],function(){return ca})})();}()
