!function(){/*

 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
"undefined"!==typeof window&&(window.PR_SHOULD_USE_CONTINUATION=!0);
(function(){function V(c){function e(a){var n=a.charCodeAt(0);if(92!==n)return n;var g=a.charAt(1);return(n=z[g])?n:"0"<=g&&"7">=g?parseInt(a.substring(1),8):"u"===g||"x"===g?parseInt(a.substring(2),16):a.charCodeAt(1)}function h(a){if(32>a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);return"\\"===a||"-"===a||"]"===a||"^"===a?"\\"+a:a}function k(a){var n=a.substring(1,a.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));
a=[];var g="^"===n[0],l=["["];g&&l.push("^");g=g?1:0;for(var f=n.length;g<f;++g){var b=n[g];if(/\\[bdsw]/i.test(b))l.push(b);else{b=e(b);if(g+2<f&&"-"===n[g+1]){var m=e(n[g+2]);g+=2}else m=b;a.push([b,m]);65>m||122<b||(65>m||90<b||a.push([Math.max(65,b)|32,Math.min(m,90)|32]),97>m||122<b||a.push([Math.max(97,b)&-33,Math.min(m,122)&-33]))}}a.sort(function(q,u){return q[0]-u[0]||u[1]-q[1]});n=[];f=[];for(g=0;g<a.length;++g)b=a[g],b[0]<=f[1]+1?f[1]=Math.max(f[1],b[1]):n.push(f=b);for(g=0;g<n.length;++g)b=
n[g],l.push(h(b[0])),b[1]>b[0]&&(b[1]+1>b[0]&&l.push("-"),l.push(h(b[1])));l.push("]");return l.join("")}function v(a){for(var n=a.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),g=n.length,l=[],f=0,b=0;f<g;++f){var m=n[f];"("===m?++b:"\\"===m.charAt(0)&&(m=+m.substring(1))&&(m<=b?l[m]=-1:n[f]=h(m))}for(f=1;f<l.length;++f)-1===l[f]&&(l[f]=++A);for(b=f=0;f<g;++f)m=n[f],
"("===m?(++b,l[b]||(n[f]="(?:")):"\\"===m.charAt(0)&&(m=+m.substring(1))&&m<=b&&(n[f]="\\"+l[m]);for(f=0;f<g;++f)"^"===n[f]&&"^"!==n[f+1]&&(n[f]="");if(a.ignoreCase&&w)for(f=0;f<g;++f)m=n[f],a=m.charAt(0),2<=m.length&&"["===a?n[f]=k(m):"\\"!==a&&(n[f]=m.replace(/[a-zA-Z]/g,function(q){q=q.charCodeAt(0);return"["+String.fromCharCode(q&-33,q|32)+"]"}));return n.join("")}for(var A=0,w=!1,r=!1,p=0,d=c.length;p<d;++p){var t=c[p];if(t.ignoreCase)r=!0;else if(/[a-z]/i.test(t.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,
""))){w=!0;r=!1;break}}var z={b:8,t:9,n:10,v:11,f:12,r:13},x=[];p=0;for(d=c.length;p<d;++p){t=c[p];if(t.global||t.multiline)throw Error(""+t);x.push("(?:"+v(t)+")")}return new RegExp(x.join("|"),r?"gi":"g")}function W(c,e){function h(p){var d=p.nodeType;if(1==d){if(!k.test(p.className)){for(d=p.firstChild;d;d=d.nextSibling)h(d);d=p.nodeName.toLowerCase();if("br"===d||"li"===d)v[r]="\n",w[r<<1]=A++,w[r++<<1|1]=p}}else if(3==d||4==d)d=p.nodeValue,d.length&&(d=e?d.replace(/\r\n?/g,"\n"):d.replace(/[ \t\r\n]+/g,
" "),v[r]=d,w[r<<1]=A,A+=d.length,w[r++<<1|1]=p)}var k=/(?:^|\s)nocode(?:\s|$)/,v=[],A=0,w=[],r=0;h(c);return{g:v.join("").replace(/\n$/,""),h:w}}function M(c,e,h,k,v){h&&(c={j:c,o:1,m:null,s:null,g:h,h:null,l:e,i:null},k(c),v.push.apply(v,c.i))}function X(c){for(var e=void 0,h=c.firstChild;h;h=h.nextSibling){var k=h.nodeType;e=1===k?e?c:h:3===k?Y.test(h.nodeValue)?c:e:e}return e===c?void 0:e}function I(c,e){function h(w){for(var r=w.l,p=w.j,d=[r,"pln"],t=0,z=w.g.match(v)||[],x={},a=0,n=z.length;a<
n;++a){var g=z[a],l=x[g],f=void 0;if("string"===typeof l)var b=!1;else{var m=k[g.charAt(0)];if(m)f=g.match(m[1]),l=m[0];else{for(b=0;b<A;++b)if(m=e[b],f=g.match(m[1])){l=m[0];break}f||(l="pln")}!(b=5<=l.length&&"lang-"===l.substring(0,5))||f&&"string"===typeof f[1]||(b=!1,l="src");b||(x[g]=l)}m=t;t+=g.length;if(b){b=f[1];var q=g.indexOf(b),u=q+b.length;f[2]&&(u=g.length-f[2].length,q=u-b.length);l=l.substring(5);M(p,r+m,g.substring(0,q),h,d);M(p,r+m+q,b,N(l,b),d);M(p,r+m+u,g.substring(u),h,d)}else d.push(r+
m,l)}w.i=d}var k={},v;(function(){for(var w=c.concat(e),r=[],p={},d=0,t=w.length;d<t;++d){var z=w[d],x=z[3];if(x)for(var a=x.length;0<=--a;)k[x.charAt(a)]=z;z=z[1];x=""+z;p.hasOwnProperty(x)||(r.push(z),p[x]=null)}r.push(/[\0-\uffff]/);v=V(r)})();var A=e.length;return h}function D(c){var e=[],h=[];c.tripleQuotedStrings?e.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,
"'\""]):c.multiLineStrings?e.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):e.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);c.verbatimStrings&&h.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var k=c.hashComments;k&&(c.cStyleComments?(1<k?e.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):e.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),h.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,null])):e.push(["com",/^#[^\r\n]*/,null,"#"]));c.cStyleComments&&(h.push(["com",/^\/\/[^\r\n]*/,null]),h.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));if(k=c.regexLiterals){var v=(k=1<k?"":"\n\r")?".":"[\\S\\s]";h.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*"+
(k+"])(?:[^/\\x5B\\x5C"+k+"]|\\x5C"+v+"|\\x5B(?:[^\\x5C\\x5D"+k+"]|\\x5C"+v+")*(?:\\x5D|$))+/)"))])}(k=c.types)&&h.push(["typ",k]);k=(""+c.keywords).replace(/^ | $/g,"");k.length&&h.push(["kwd",new RegExp("^(?:"+k.replace(/[\s,]+/g,"|")+")\\b"),null]);e.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);k="^.[^\\s\\w.$@'\"`/\\\\]*";c.regexLiterals&&(k+="(?!s*/)");h.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",
RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pln",/^\\[\s\S]?/,null],["pun",new RegExp(k),null]);return I(e,h)}function O(c,e,h){function k(a){var n=a.nodeType;if(1==n&&!A.test(a.className))if("br"===a.nodeName.toLowerCase())v(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)k(a);else if((3==n||4==n)&&h){var g=a.nodeValue,l=g.match(w);l&&(n=g.substring(0,l.index),a.nodeValue=n,(g=g.substring(l.index+
l[0].length))&&a.parentNode.insertBefore(r.createTextNode(g),a.nextSibling),v(a),n||a.parentNode.removeChild(a))}}function v(a){function n(l,f){f=f?l.cloneNode(!1):l;var b=l.parentNode;if(b){b=n(b,1);l=l.nextSibling;b.appendChild(f);for(var m=l;m;m=l)l=m.nextSibling,b.appendChild(m)}return f}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;a=n(a.nextSibling,0);for(var g;(g=a.parentNode)&&1===g.nodeType;)a=g;d.push(a)}for(var A=/(?:^|\s)nocode(?:\s|$)/,w=/\r\n?|\n/,r=c.ownerDocument,p=r.createElement("li");c.firstChild;)p.appendChild(c.firstChild);
for(var d=[p],t=0;t<d.length;++t)k(d[t]);e===(e|0)&&d[0].setAttribute("value",e);var z=r.createElement("ol");z.className="linenums";e=Math.max(0,e-1|0)||0;t=0;for(var x=d.length;t<x;++t)p=d[t],p.className="L"+(t+e)%10,p.firstChild||p.appendChild(r.createTextNode("\u00a0")),z.appendChild(p);c.appendChild(z)}function C(c,e){for(var h=e.length;0<=--h;){var k=e[h];K.hasOwnProperty(k)?E.console&&console.warn("cannot override language handler %s",k):K[k]=c}}function N(c,e){c&&K.hasOwnProperty(c)||(c=/^\s*</.test(e)?
"default-markup":"default-code");return K[c]}function P(c){var e=c.m;try{var h=W(c.j,c.o),k=h.g;c.g=k;c.h=h.h;c.l=0;N(e,k)(c);var v=/\bMSIE\s(\d+)/.exec(navigator.userAgent);v=v&&8>=+v[1];e=/\n/g;var A=c.g,w=A.length;h=0;var r=c.h,p=r.length;k=0;var d=c.i,t=d.length,z=0;d[t]=w;var x,a;for(a=x=0;a<t;)d[a]!==d[a+2]?(d[x++]=d[a++],d[x++]=d[a++]):a+=2;t=x;for(a=x=0;a<t;){for(var n=d[a],g=d[a+1],l=a+2;l+2<=t&&d[l+1]===g;)l+=2;d[x++]=n;d[x++]=g;a=l}d.length=x;var f=c.j;c="";f&&(c=f.style.display,f.style.display=
"none");try{for(;k<p;){var b=r[k+2]||w,m=d[z+2]||w;l=Math.min(b,m);var q=r[k+1],u;if(1!==q.nodeType&&(u=A.substring(h,l))){v&&(u=u.replace(e,"\r"));q.nodeValue=u;var y=q.ownerDocument,F=y.createElement("span");F.className=d[z+1];var B=q.parentNode;B.replaceChild(F,q);F.appendChild(q);h<b&&(r[k+1]=q=y.createTextNode(A.substring(l,b)),B.insertBefore(q,F.nextSibling))}h=l;h>=b&&(k+=2);h>=m&&(z+=2)}}finally{f&&(f.style.display=c)}}catch(L){E.console&&console.log(L&&L.stack||L)}}var E="undefined"!==typeof window?
window:{},G=["break,continue,do,else,for,if,return,while"],H=[[G,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,restrict,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],J=[H,"alignas,alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,noexcept,noreturn,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
Q=[H,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],R=[H,"abstract,add,alias,as,ascending,async,await,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,get,global,group,implicit,in,interface,internal,into,is,join,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,remove,sbyte,sealed,select,set,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,value,var,virtual,where,yield"];
H=[H,"abstract,async,await,constructor,debugger,enum,eval,export,from,function,get,import,implements,instanceof,interface,let,null,of,set,undefined,var,with,yield,Infinity,NaN"];var S=[G,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],T=[G,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"];
G=[G,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"];var U=/^(DIR|FILE|array|vector|(de|priority_)?queue|(forward_)?list|stack|(const_)?(reverse_)?iterator|(unordered_)?(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,Y=/\S/,Z=D({keywords:[J,R,Q,H,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",S,T,G],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),
K={};C(Z,["default-code"]);C(I([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));C(I([["pln",/^[\s]+/,
null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);C(I([],[["atv",/^[\s\S]+/]]),
["uq.val"]);C(D({keywords:J,hashComments:!0,cStyleComments:!0,types:U}),"c cc cpp cxx cyc m".split(" "));C(D({keywords:"null,true,false"}),["json"]);C(D({keywords:R,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:U}),["cs"]);C(D({keywords:Q,cStyleComments:!0}),["java"]);C(D({keywords:G,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);C(D({keywords:S,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);C(D({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",
hashComments:!0,multiLineStrings:!0,regexLiterals:2}),["perl","pl","pm"]);C(D({keywords:T,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);C(D({keywords:H,cStyleComments:!0,regexLiterals:!0}),["javascript","js","ts","typescript"]);C(D({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,
regexLiterals:!0}),["coffee"]);C(I([],[["str",/^[\s\S]+/]]),["regex"]);var ca=E.PR={createSimpleLexer:I,registerLangHandler:C,sourceDecorator:D,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:E.prettyPrintOne=function(c,e,h){h=h||!1;e=e||null;var k=document.createElement("div");k.innerHTML="<pre>"+c+"</pre>";
k=k.firstChild;h&&O(k,h,!0);P({m:e,s:h,j:k,o:1,g:null,l:null,h:null,i:null});return k.innerHTML},prettyPrint:E.prettyPrint=function(c,e){function h(){for(var f=E.PR_SHOULD_USE_CONTINUATION?p.now()+250:Infinity;d<v.length&&p.now()<f;d++){for(var b=v[d],m=l,q=b;q=q.previousSibling;){var u=q.nodeType,y=(7===u||8===u)&&q.nodeValue;if(y?!/^\??prettify\b/.test(y):3!==u||/\S/.test(q.nodeValue))break;if(y){m={};y.replace(/\b(\w+)=([\w:.%+-]+)/g,function(L,aa,ba){m[aa]=ba});break}}q=b.className;if((m!==l||
z.test(q))&&!x.test(q)){u=!1;for(y=b.parentNode;y;y=y.parentNode)if(g.test(y.tagName)&&y.className&&z.test(y.className)){u=!0;break}if(!u){b.className+=" prettyprinted";u=m.lang;if(!u){u=q.match(t);var F;!u&&(F=X(b))&&n.test(F.tagName)&&(u=F.className.match(t));u&&=u[1]}if(a.test(b.tagName))y=1;else{y=b.currentStyle;var B=k.defaultView;y=(y=y?y.whiteSpace:B&&B.getComputedStyle?B.getComputedStyle(b,null).getPropertyValue("white-space"):0)&&"pre"===y.substring(0,3)}B=m.linenums;(B="true"===B||+B)||
(B=(B=q.match(/\blinenums\b(?::(\d+))?/))?B[1]&&B[1].length?+B[1]:!0:!1);B&&O(b,B,y);P({m:u,j:b,s:B,o:y,g:null,l:null,h:null,i:null})}}}d<v.length?E.setTimeout(h,250):"function"===typeof c&&c()}e=e||document.body;var k=e.ownerDocument||document;e=[e.getElementsByTagName("pre"),e.getElementsByTagName("code"),e.getElementsByTagName("xmp")];for(var v=[],A=0;A<e.length;++A)for(var w=0,r=e[A].length;w<r;++w)v.push(e[A][w]);e=null;var p=Date;p.now||(p={now:function(){return+new Date}});var d=0,t=/\blang(?:uage)?-([\w.]+)(?!\S)/,
z=/\bprettyprint\b/,x=/\bprettyprinted\b/,a=/pre|xmp/i,n=/^code$/i,g=/^(?:pre|code|xmp)$/i,l={};h()}};J=E.define;"function"===typeof J&&J.amd&&J("google-code-prettify",[],function(){return ca})})();}()
