!function(){/*

 Copyright (C) 2013 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
(function(){function pa(u){function D(){try{Z.doScroll("left")}catch(M){J.setTimeout(D,50);return}C("poll")}function C(M){if("readystatechange"!=M.type||"complete"==H.readyState)("load"==M.type?J:H)[W](B+M.type,C,!1),!K&&(K=!0)&&u.call(J,M.type||M)}var I=H.addEventListener,K=!1,N=!0,G=I?"addEventListener":"attachEvent",W=I?"removeEventListener":"detachEvent",B=I?"":"on";if("complete"==H.readyState)u.call(J,"lazy");else{if(H.createEventObject&&Z.doScroll){try{N=!J.frameElement}catch(M){}N&&D()}H[G](B+
"DOMContentLoaded",C,!1);H[G](B+"readystatechange",C,!1);J[G](B+"load",C,!1)}}function fa(){ha&&pa(function(){var u=aa.length;qa(u?function(){for(var D=0;D<u;++D)(function(C){J.setTimeout(function(){J.exports[aa[C]].apply(J,arguments)},0)})(D)}:void 0)})}for(var J=window,H=document,Z=H.documentElement,ba=H.head||H.getElementsByTagName("head")[0]||Z,R="",S=H.getElementsByTagName("script"),L=S.length;0<=--L;){var ca=S[L],ia=ca.src.match(/^[^?#]*\/run_prettify\.js(\?[^#]*)?(?:#.*)?$/);if(ia){R=ia[1]||
"";ca.parentNode.removeChild(ca);break}}var ha=!0,V=[],da=[],aa=[];R.replace(/[?&]([^&=]+)=([^&]+)/g,function(u,D,C){C=decodeURIComponent(C);D=decodeURIComponent(D);"autorun"==D?ha=!/^[0fn]/i.test(C):"lang"==D?V.push(C):"skin"==D?da.push(C):"callback"==D&&aa.push(C)});L=0;for(R=V.length;L<R;++L)(function(){var u=H.createElement("script");u.onload=u.onerror=u.onreadystatechange=function(){!u||u.readyState&&!/loaded|complete/.test(u.readyState)||(u.onerror=u.onload=u.onreadystatechange=null,--ea,ea||
J.setTimeout(fa,0),u.parentNode&&u.parentNode.removeChild(u),u=null)};u.type="text/javascript";u.src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/lang-"+encodeURIComponent(V[L])+".js";ba.insertBefore(u,ba.firstChild)})(V[L]);var ea=V.length;S=[];L=0;for(R=da.length;L<R;++L)S.push("https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/skins/"+encodeURIComponent(da[L])+".css");S.push("https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/prettify.css");(function(u){function D(I){if(I!==
C){var K=H.createElement("link");K.rel="stylesheet";K.type="text/css";I+1<C&&(K.error=K.onerror=function(){D(I+1)});K.href=u[I];ba.appendChild(K)}}var C=u.length;D(0)})(S);var qa=function(){"undefined"!==typeof window&&(window.PR_SHOULD_USE_CONTINUATION=!0);var u;(function(){function D(c){function e(a){var n=a.charCodeAt(0);if(92!==n)return n;var g=a.charAt(1);return(n=A[g])?n:"0"<=g&&"7">=g?parseInt(a.substring(1),8):"u"===g||"x"===g?parseInt(a.substring(2),16):a.charCodeAt(1)}function h(a){if(32>
a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);return"\\"===a||"-"===a||"]"===a||"^"===a?"\\"+a:a}function k(a){var n=a.substring(1,a.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));a=[];var g="^"===n[0],l=["["];g&&l.push("^");g=g?1:0;for(var f=n.length;g<f;++g){var b=n[g];if(/\\[bdsw]/i.test(b))l.push(b);else{b=e(b);if(g+2<f&&"-"===n[g+1]){var m=e(n[g+2]);g+=2}else m=b;a.push([b,m]);65>m||122<b||
(65>m||90<b||a.push([Math.max(65,b)|32,Math.min(m,90)|32]),97>m||122<b||a.push([Math.max(97,b)&-33,Math.min(m,122)&-33]))}}a.sort(function(q,v){return q[0]-v[0]||v[1]-q[1]});n=[];f=[];for(g=0;g<a.length;++g)b=a[g],b[0]<=f[1]+1?f[1]=Math.max(f[1],b[1]):n.push(f=b);for(g=0;g<n.length;++g)b=n[g],l.push(h(b[0])),b[1]>b[0]&&(b[1]+1>b[0]&&l.push("-"),l.push(h(b[1])));l.push("]");return l.join("")}function w(a){for(var n=a.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)",
"g")),g=n.length,l=[],f=0,b=0;f<g;++f){var m=n[f];"("===m?++b:"\\"===m.charAt(0)&&(m=+m.substring(1))&&(m<=b?l[m]=-1:n[f]=h(m))}for(f=1;f<l.length;++f)-1===l[f]&&(l[f]=++E);for(b=f=0;f<g;++f)m=n[f],"("===m?(++b,l[b]||(n[f]="(?:")):"\\"===m.charAt(0)&&(m=+m.substring(1))&&m<=b&&(n[f]="\\"+l[m]);for(f=0;f<g;++f)"^"===n[f]&&"^"!==n[f+1]&&(n[f]="");if(a.ignoreCase&&x)for(f=0;f<g;++f)m=n[f],a=m.charAt(0),2<=m.length&&"["===a?n[f]=k(m):"\\"!==a&&(n[f]=m.replace(/[a-zA-Z]/g,function(q){q=q.charCodeAt(0);
return"["+String.fromCharCode(q&-33,q|32)+"]"}));return n.join("")}for(var E=0,x=!1,r=!1,p=0,d=c.length;p<d;++p){var t=c[p];if(t.ignoreCase)r=!0;else if(/[a-z]/i.test(t.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){x=!0;r=!1;break}}var A={b:8,t:9,n:10,v:11,f:12,r:13},y=[];p=0;for(d=c.length;p<d;++p){t=c[p];if(t.global||t.multiline)throw Error(""+t);y.push("(?:"+w(t)+")")}return new RegExp(y.join("|"),r?"gi":"g")}function C(c,e){function h(p){var d=p.nodeType;if(1==d){if(!k.test(p.className)){for(d=
p.firstChild;d;d=d.nextSibling)h(d);d=p.nodeName.toLowerCase();if("br"===d||"li"===d)w[r]="\n",x[r<<1]=E++,x[r++<<1|1]=p}}else if(3==d||4==d)d=p.nodeValue,d.length&&(d=e?d.replace(/\r\n?/g,"\n"):d.replace(/[ \t\r\n]+/g," "),w[r]=d,x[r<<1]=E,E+=d.length,x[r++<<1|1]=p)}var k=/(?:^|\s)nocode(?:\s|$)/,w=[],E=0,x=[],r=0;h(c);return{g:w.join("").replace(/\n$/,""),h:x}}function I(c,e,h,k,w){h&&(c={j:c,o:1,m:null,s:null,g:h,h:null,l:e,i:null},k(c),w.push.apply(w,c.i))}function K(c){for(var e=void 0,h=c.firstChild;h;h=
h.nextSibling){var k=h.nodeType;e=1===k?e?c:h:3===k?ra.test(h.nodeValue)?c:e:e}return e===c?void 0:e}function N(c,e){function h(x){for(var r=x.l,p=x.j,d=[r,"pln"],t=0,A=x.g.match(w)||[],y={},a=0,n=A.length;a<n;++a){var g=A[a],l=y[g],f=void 0;if("string"===typeof l)var b=!1;else{var m=k[g.charAt(0)];if(m)f=g.match(m[1]),l=m[0];else{for(b=0;b<E;++b)if(m=e[b],f=g.match(m[1])){l=m[0];break}f||(l="pln")}!(b=5<=l.length&&"lang-"===l.substring(0,5))||f&&"string"===typeof f[1]||(b=!1,l="src");b||(y[g]=l)}m=
t;t+=g.length;if(b){b=f[1];var q=g.indexOf(b),v=q+b.length;f[2]&&(v=g.length-f[2].length,q=v-b.length);l=l.substring(5);I(p,r+m,g.substring(0,q),h,d);I(p,r+m+q,b,M(l,b),d);I(p,r+m+v,g.substring(v),h,d)}else d.push(r+m,l)}x.i=d}var k={},w;(function(){for(var x=c.concat(e),r=[],p={},d=0,t=x.length;d<t;++d){var A=x[d],y=A[3];if(y)for(var a=y.length;0<=--a;)k[y.charAt(a)]=A;A=A[1];y=""+A;p.hasOwnProperty(y)||(r.push(A),p[y]=null)}r.push(/[\0-\uffff]/);w=D(r)})();var E=e.length;return h}function G(c){var e=
[],h=[];c.tripleQuotedStrings?e.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):c.multiLineStrings?e.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):e.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);c.verbatimStrings&&h.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,
null]);var k=c.hashComments;k&&(c.cStyleComments?(1<k?e.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):e.push(["com",/^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),h.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h(?:h|pp|\+\+)?|[a-z]\w*)>/,null])):e.push(["com",/^#[^\r\n]*/,null,"#"]));c.cStyleComments&&(h.push(["com",/^\/\/[^\r\n]*/,null]),h.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));if(k=c.regexLiterals){var w=
(k=1<k?"":"\n\r")?".":"[\\S\\s]";h.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*"+(k+"])(?:[^/\\x5B\\x5C"+k+"]|\\x5C"+w+"|\\x5B(?:[^\\x5C\\x5D"+k+"]|\\x5C"+w+")*(?:\\x5D|$))+/)"))])}(k=c.types)&&h.push(["typ",k]);k=(""+c.keywords).replace(/^ | $/g,"");k.length&&h.push(["kwd",new RegExp("^(?:"+k.replace(/[\s,]+/g,
"|")+")\\b"),null]);e.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);k="^.[^\\s\\w.$@'\"`/\\\\]*";c.regexLiterals&&(k+="(?!s*/)");h.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pln",/^\\[\s\S]?/,null],["pun",new RegExp(k),null]);return N(e,h)}function W(c,e,h){function k(a){var n=a.nodeType;
if(1==n&&!E.test(a.className))if("br"===a.nodeName.toLowerCase())w(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)k(a);else if((3==n||4==n)&&h){var g=a.nodeValue,l=g.match(x);l&&(n=g.substring(0,l.index),a.nodeValue=n,(g=g.substring(l.index+l[0].length))&&a.parentNode.insertBefore(r.createTextNode(g),a.nextSibling),w(a),n||a.parentNode.removeChild(a))}}function w(a){function n(l,f){f=f?l.cloneNode(!1):l;var b=l.parentNode;if(b){b=n(b,1);l=l.nextSibling;b.appendChild(f);
for(var m=l;m;m=l)l=m.nextSibling,b.appendChild(m)}return f}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;a=n(a.nextSibling,0);for(var g;(g=a.parentNode)&&1===g.nodeType;)a=g;d.push(a)}for(var E=/(?:^|\s)nocode(?:\s|$)/,x=/\r\n?|\n/,r=c.ownerDocument,p=r.createElement("li");c.firstChild;)p.appendChild(c.firstChild);for(var d=[p],t=0;t<d.length;++t)k(d[t]);e===(e|0)&&d[0].setAttribute("value",e);var A=r.createElement("ol");A.className="linenums";e=Math.max(0,e-1|0)||0;t=0;for(var y=d.length;t<y;++t)p=
d[t],p.className="L"+(t+e)%10,p.firstChild||p.appendChild(r.createTextNode("\u00a0")),A.appendChild(p);c.appendChild(A)}function B(c,e){for(var h=e.length;0<=--h;){var k=e[h];X.hasOwnProperty(k)?T.console&&console.warn("cannot override language handler %s",k):X[k]=c}}function M(c,e){c&&X.hasOwnProperty(c)||(c=/^\s*</.test(e)?"default-markup":"default-code");return X[c]}function ja(c){var e=c.m;try{var h=C(c.j,c.o),k=h.g;c.g=k;c.h=h.h;c.l=0;M(e,k)(c);var w=/\bMSIE\s(\d+)/.exec(navigator.userAgent);
w=w&&8>=+w[1];e=/\n/g;var E=c.g,x=E.length;h=0;var r=c.h,p=r.length;k=0;var d=c.i,t=d.length,A=0;d[t]=x;var y,a;for(a=y=0;a<t;)d[a]!==d[a+2]?(d[y++]=d[a++],d[y++]=d[a++]):a+=2;t=y;for(a=y=0;a<t;){for(var n=d[a],g=d[a+1],l=a+2;l+2<=t&&d[l+1]===g;)l+=2;d[y++]=n;d[y++]=g;a=l}d.length=y;var f=c.j;c="";f&&(c=f.style.display,f.style.display="none");try{for(;k<p;){var b=r[k+2]||x,m=d[A+2]||x;l=Math.min(b,m);var q=r[k+1],v;if(1!==q.nodeType&&(v=E.substring(h,l))){w&&(v=v.replace(e,"\r"));q.nodeValue=v;var z=
q.ownerDocument,O=z.createElement("span");O.className=d[A+1];var F=q.parentNode;F.replaceChild(O,q);O.appendChild(q);h<b&&(r[k+1]=q=z.createTextNode(E.substring(l,b)),F.insertBefore(q,O.nextSibling))}h=l;h>=b&&(k+=2);h>=m&&(A+=2)}}finally{f&&(f.style.display=c)}}catch(Y){T.console&&console.log(Y&&Y.stack||Y)}}var T="undefined"!==typeof window?window:{},P=["break,continue,do,else,for,if,return,while"],Q=[[P,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,restrict,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],
"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],U=[Q,"alignas,alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,noexcept,noreturn,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],ka=[Q,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],
la=[Q,"abstract,add,alias,as,ascending,async,await,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,get,global,group,implicit,in,interface,internal,into,is,join,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,remove,sbyte,sealed,select,set,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,value,var,virtual,where,yield"];Q=[Q,"abstract,async,await,constructor,debugger,enum,eval,export,from,function,get,import,implements,instanceof,interface,let,null,of,set,undefined,var,with,yield,Infinity,NaN"];
var ma=[P,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],na=[P,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"];P=[P,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"];var oa=/^(DIR|FILE|array|vector|(de|priority_)?queue|(forward_)?list|stack|(const_)?(reverse_)?iterator|(unordered_)?(multi)?(set|map)|bitset|u?(int|float)\d*)\b/,
ra=/\S/,sa=G({keywords:[U,la,ka,Q,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",ma,na,P],hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),X={};B(sa,["default-code"]);B(N([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],
["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));B(N([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],
["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);B(N([],[["atv",/^[\s\S]+/]]),["uq.val"]);B(G({keywords:U,hashComments:!0,cStyleComments:!0,types:oa}),"c cc cpp cxx cyc m".split(" "));B(G({keywords:"null,true,false"}),["json"]);B(G({keywords:la,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,
types:oa}),["cs"]);B(G({keywords:ka,cStyleComments:!0}),["java"]);B(G({keywords:P,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);B(G({keywords:ma,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py","python"]);B(G({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:2}),["perl","pl",
"pm"]);B(G({keywords:na,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);B(G({keywords:Q,cStyleComments:!0,regexLiterals:!0}),["javascript","js","ts","typescript"]);B(G({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);B(N([],[["str",/^[\s\S]+/]]),
["regex"]);var va=T.PR={createSimpleLexer:N,registerLangHandler:B,sourceDecorator:G,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:function(c,e,h){h=h||!1;e=e||null;var k=document.createElement("div");k.innerHTML="<pre>"+c+"</pre>";k=k.firstChild;h&&W(k,h,!0);ja({m:e,s:h,j:k,o:1,g:null,l:null,h:null,i:null});
return k.innerHTML},prettyPrint:u=function(c,e){function h(){for(var f=T.PR_SHOULD_USE_CONTINUATION?p.now()+250:Infinity;d<w.length&&p.now()<f;d++){for(var b=w[d],m=l,q=b;q=q.previousSibling;){var v=q.nodeType,z=(7===v||8===v)&&q.nodeValue;if(z?!/^\??prettify\b/.test(z):3!==v||/\S/.test(q.nodeValue))break;if(z){m={};z.replace(/\b(\w+)=([\w:.%+-]+)/g,function(Y,ta,ua){m[ta]=ua});break}}q=b.className;if((m!==l||A.test(q))&&!y.test(q)){v=!1;for(z=b.parentNode;z;z=z.parentNode)if(g.test(z.tagName)&&z.className&&
A.test(z.className)){v=!0;break}if(!v){b.className+=" prettyprinted";v=m.lang;if(!v){v=q.match(t);var O;!v&&(O=K(b))&&n.test(O.tagName)&&(v=O.className.match(t));v&&=v[1]}if(a.test(b.tagName))z=1;else{z=b.currentStyle;var F=k.defaultView;z=(z=z?z.whiteSpace:F&&F.getComputedStyle?F.getComputedStyle(b,null).getPropertyValue("white-space"):0)&&"pre"===z.substring(0,3)}F=m.linenums;(F="true"===F||+F)||(F=(F=q.match(/\blinenums\b(?::(\d+))?/))?F[1]&&F[1].length?+F[1]:!0:!1);F&&W(b,F,z);ja({m:v,j:b,s:F,
o:z,g:null,l:null,h:null,i:null})}}}d<w.length?T.setTimeout(h,250):"function"===typeof c&&c()}e=e||document.body;var k=e.ownerDocument||document;e=[e.getElementsByTagName("pre"),e.getElementsByTagName("code"),e.getElementsByTagName("xmp")];for(var w=[],E=0;E<e.length;++E)for(var x=0,r=e[E].length;x<r;++x)w.push(e[E][x]);e=null;var p=Date;p.now||(p={now:function(){return+new Date}});var d=0,t=/\blang(?:uage)?-([\w.]+)(?!\S)/,A=/\bprettyprint\b/,y=/\bprettyprinted\b/,a=/pre|xmp/i,n=/^code$/i,g=/^(?:pre|code|xmp)$/i,
l={};h()}};U=T.define;"function"===typeof U&&U.amd&&U("google-code-prettify",[],function(){return va})})();return u}();ea||J.setTimeout(fa,0)})();}()
