!function(){/*

 Copyright (C) 2013 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
(function(){function qa(u){function E(){try{Z.doScroll("left")}catch(M){J.setTimeout(E,50);return}D("poll")}function D(M){if("readystatechange"!=M.type||"complete"==H.readyState)("load"==M.type?J:H)[W](C+M.type,D,!1),!K&&(K=!0)&&u.call(J,M.type||M)}var I=H.addEventListener,K=!1,N=!0,F=I?"addEventListener":"attachEvent",W=I?"removeEventListener":"detachEvent",C=I?"":"on";if("complete"==H.readyState)u.call(J,"lazy");else{if(H.createEventObject&&Z.doScroll){try{N=!J.frameElement}catch(M){}N&&E()}H[F](C+
"DOMContentLoaded",D,!1);H[F](C+"readystatechange",D,!1);J[F](C+"load",D,!1)}}function ha(){ia&&qa(function(){var u=aa.length;ra(u?function(){for(var E=0;E<u;++E)(function(D){J.setTimeout(function(){J.exports[aa[D]].apply(J,arguments)},0)})(E)}:void 0)})}for(var J=window,H=document,Z=H.documentElement,ba=H.head||H.getElementsByTagName("head")[0]||Z,Q="",R=H.getElementsByTagName("script"),L=R.length;0<=--L;){var ca=R[L],ja=ca.src.match(/^[^?#]*\/run_prettify\.js(\?[^#]*)?(?:#.*)?$/);if(ja){Q=ja[1]||
"";ca.parentNode.removeChild(ca);break}}var ia=!0,V=[],da=[],aa=[];Q.replace(/[?&]([^&=]+)=([^&]+)/g,function(u,E,D){D=decodeURIComponent(D);E=decodeURIComponent(E);"autorun"==E?ia=!/^[0fn]/i.test(D):"lang"==E?V.push(D):"skin"==E?da.push(D):"callback"==E&&aa.push(D)});L=0;for(Q=V.length;L<Q;++L)(function(){var u=H.createElement("script");u.onload=u.onerror=u.onreadystatechange=function(){!u||u.readyState&&!/loaded|complete/.test(u.readyState)||(u.onerror=u.onload=u.onreadystatechange=null,--ea,ea||
J.setTimeout(ha,0),u.parentNode&&u.parentNode.removeChild(u),u=null)};u.type="text/javascript";u.src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/lang-"+encodeURIComponent(V[L])+".js";ba.insertBefore(u,ba.firstChild)})(V[L]);var ea=V.length;R=[];L=0;for(Q=da.length;L<Q;++L)R.push("https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/skins/"+encodeURIComponent(da[L])+".css");R.push("https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/prettify.css");(function(u){function E(I){if(I!==
D){var K=H.createElement("link");K.rel="stylesheet";K.type="text/css";I+1<D&&(K.error=K.onerror=function(){E(I+1)});K.href=u[I];ba.appendChild(K)}}var D=u.length;E(0)})(R);var ra=function(){"undefined"!==typeof window&&(window.PR_SHOULD_USE_CONTINUATION=!0);var u;(function(){function E(d){function c(a){var n=a.charCodeAt(0);if(92!==n)return n;var f=a.charAt(1);return(n=z[f])?n:"0"<=f&&"7">=f?parseInt(a.substring(1),8):"u"===f||"x"===f?parseInt(a.substring(2),16):a.charCodeAt(1)}function g(a){if(32>
a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);return"\\"===a||"-"===a||"]"===a||"^"===a?"\\"+a:a}function l(a){var n=(new RegExpCompat("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"))[Symbol.match](a.substring(1,a.length-1));a=[];var f="^"===n[0],h=["["];f&&h.push("^");f=f?1:0;for(var e=n.length;f<e;++f){var b=n[f];if((new RegExpCompat("\\\\[bdsw]","i")).test(b))h.push(b);else{b=c(b);if(f+2<e&&"-"===n[f+1]){var k=c(n[f+
2]);f+=2}else k=b;a.push([b,k]);65>k||122<b||(65>k||90<b||a.push([Math.max(65,b)|32,Math.min(k,90)|32]),97>k||122<b||a.push([Math.max(97,b)&-33,Math.min(k,122)&-33]))}}a.sort(function(r,v){return r[0]-v[0]||v[1]-r[1]});n=[];e=[];for(f=0;f<a.length;++f)b=a[f],b[0]<=e[1]+1?e[1]=Math.max(e[1],b[1]):n.push(e=b);for(f=0;f<n.length;++f)b=n[f],h.push(g(b[0])),b[1]>b[0]&&(b[1]+1>b[0]&&h.push("-"),h.push(g(b[1])));h.push("]");return h.join("")}function w(a){for(var n=(new RegExpCompat("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)",
"g"))[Symbol.match](a.source),f=n.length,h=[],e=0,b=0;e<f;++e){var k=n[e];"("===k?++b:"\\"===k.charAt(0)&&(k=+k.substring(1))&&(k<=b?h[k]=-1:n[e]=g(k))}for(e=1;e<h.length;++e)-1===h[e]&&(h[e]=++G);for(b=e=0;e<f;++e)k=n[e],"("===k?(++b,h[b]||(n[e]="(?:")):"\\"===k.charAt(0)&&(k=+k.substring(1))&&k<=b&&(n[e]="\\"+h[k]);for(e=0;e<f;++e)"^"===n[e]&&"^"!==n[e+1]&&(n[e]="");if(a.ignoreCase&&x)for(e=0;e<f;++e)k=n[e],a=k.charAt(0),2<=k.length&&"["===a?n[e]=l(k):"\\"!==a&&(n[e]=(new RegExpCompat("[a-zA-Z]",
"g"))[Symbol.replace](k,function(r){r=r.charCodeAt(0);return"["+String.fromCharCode(r&-33,r|32)+"]"}));return n.join("")}for(var G=0,x=!1,t=!1,q=0,m=d.length;q<m;++q){var p=d[q];if(p.ignoreCase)t=!0;else if((new RegExpCompat("[a-z]","i")).test((new RegExpCompat("\\\\u[0-9a-f]{4}|\\\\x[0-9a-f]{2}|\\\\[^ux]","gi"))[Symbol.replace](p.source,""))){x=!0;t=!1;break}}var z={b:8,t:9,n:10,v:11,f:12,r:13},y=[];q=0;for(m=d.length;q<m;++q){p=d[q];if(p.global||p.multiline)throw Error(""+p);y.push("(?:"+w(p)+")")}return new RegExpCompat(y.join("|"),
t?"gi":"g")}function D(d,c){function g(q){var m=q.nodeType;if(1==m){if(!l.test(q.className)){for(m=q.firstChild;m;m=m.nextSibling)g(m);m=q.nodeName.toLowerCase();if("br"===m||"li"===m)w[t]="\n",x[t<<1]=G++,x[t++<<1|1]=q}}else if(3==m||4==m)m=q.nodeValue,m.length&&(m=c?(new RegExpCompat("\\r\\n?","g"))[Symbol.replace](m,"\n"):(new RegExpCompat("[ \\t\\r\\n]+","g"))[Symbol.replace](m," "),w[t]=m,x[t<<1]=G,G+=m.length,x[t++<<1|1]=q)}var l=RegExpCompat("(?:^|\\s)nocode(?:\\s|$)"),w=[],G=0,x=[],t=0;g(d);
return{g:(new RegExpCompat("\\n$"))[Symbol.replace](w.join(""),""),h:x}}function I(d,c,g,l,w){g&&(d={j:d,o:1,m:null,s:null,g,h:null,l:c,i:null},l(d),w.push.apply(w,d.i))}function K(d){for(var c=void 0,g=d.firstChild;g;g=g.nextSibling){var l=g.nodeType;c=1===l?c?d:g:3===l?sa.test(g.nodeValue)?d:c:c}return c===d?void 0:c}function N(d,c){function g(x){for(var t=x.l,q=x.j,m=[t,"pln"],p=0,z=w[Symbol.match](x.g)||[],y={},a=0,n=z.length;a<n;++a){var f=z[a],h=y[f],e=void 0;if("string"===typeof h)var b=!1;
else{var k=l[f.charAt(0)];if(k)e=k[1][Symbol.match](f),h=k[0];else{for(b=0;b<G;++b)if(k=c[b],e=k[1][Symbol.match](f)){h=k[0];break}e||(h="pln")}!(b=5<=h.length&&"lang-"===h.substring(0,5))||e&&"string"===typeof e[1]||(b=!1,h="src");b||(y[f]=h)}k=p;p+=f.length;if(b){b=e[1];var r=f.indexOf(b),v=r+b.length;e[2]&&(v=f.length-e[2].length,r=v-b.length);h=h.substring(5);I(q,t+k,f.substring(0,r),g,m);I(q,t+k+r,b,M(h,b),m);I(q,t+k+v,f.substring(v),g,m)}else m.push(t+k,h)}x.i=m}var l={},w;(function(){for(var x=
d.concat(c),t=[],q={},m=0,p=x.length;m<p;++m){var z=x[m],y=z[3];if(y)for(var a=y.length;0<=--a;)l[y.charAt(a)]=z;z=z[1];y=""+z;q.hasOwnProperty(y)||(t.push(z),q[y]=null)}t.push(new RegExpCompat("[\x00-\uffff]"));w=E(t)})();var G=c.length;return g}function F(d){var c=[],g=[];d.tripleQuotedStrings?c.push(["str",new RegExpCompat("^(?:\\'\\'\\'(?:[^\\'\\\\]|\\\\[\\s\\S]|\\'{1,2}(?=[^\\']))*(?:\\'\\'\\'|$)|\\\"\\\"\\\"(?:[^\\\"\\\\]|\\\\[\\s\\S]|\\\"{1,2}(?=[^\\\"]))*(?:\\\"\\\"\\\"|$)|\\'(?:[^\\\\\\']|\\\\[\\s\\S])*(?:\\'|$)|\\\"(?:[^\\\\\\\"]|\\\\[\\s\\S])*(?:\\\"|$))"),
null,"'\""]):d.multiLineStrings?c.push(["str",new RegExpCompat("^(?:\\'(?:[^\\\\\\']|\\\\[\\s\\S])*(?:\\'|$)|\\\"(?:[^\\\\\\\"]|\\\\[\\s\\S])*(?:\\\"|$)|\\`(?:[^\\\\\\`]|\\\\[\\s\\S])*(?:\\`|$))"),null,"'\"`"]):c.push(["str",new RegExpCompat("^(?:\\'(?:[^\\\\\\'\\r\\n]|\\\\.)*(?:\\'|$)|\\\"(?:[^\\\\\\\"\\r\\n]|\\\\.)*(?:\\\"|$))"),null,"\"'"]);d.verbatimStrings&&g.push(["str",new RegExpCompat('^@\\"(?:[^\\"]|\\"\\")*(?:\\"|$)'),null]);var l=d.hashComments;l&&(d.cStyleComments?(1<l?c.push(["com",new RegExpCompat("^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)"),
null,"#"]):c.push(["com",new RegExpCompat("^#(?:(?:define|e(?:l|nd)if|else|error|ifn?def|include|line|pragma|undef|warning)\\b|[^\\r\\n]*)"),null,"#"]),g.push(["str",new RegExpCompat("^<(?:(?:(?:\\.\\.\\/)*|\\/?)(?:[\\w-]+(?:\\/[\\w-]+)+)?[\\w-]+\\.h(?:h|pp|\\+\\+)?|[a-z]\\w*)>"),null])):c.push(["com",new RegExpCompat("^#[^\\r\\n]*"),null,"#"]));d.cStyleComments&&(g.push(["com",new RegExpCompat("^\\/\\/[^\\r\\n]*"),null]),g.push(["com",new RegExpCompat("^\\/\\*[\\s\\S]*?(?:\\*\\/|$)"),null]));if(l=
d.regexLiterals){var w=(l=1<l?"":"\n\r")?".":"[\\S\\s]";g.push(["lang-regex",new RegExpCompat("^(?:^^\\.?|[+-]|[!=]=?=?|\\#|%=?|&&?=?|\\(|\\*=?|[+\\-]=|->|\\/=?|::?|<<?=?|>>?>?=?|,|;|\\?|@|\\[|~|{|\\^\\^?=?|\\|\\|?=?|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*"+(l+"])(?:[^/\\x5B\\x5C"+l+"]|\\x5C"+w+"|\\x5B(?:[^\\x5C\\x5D"+l+"]|\\x5C"+w+")*(?:\\x5D|$))+/)"))])}(l=d.types)&&g.push(["typ",l]);l=(new RegExpCompat("^ | $","g"))[Symbol.replace](""+d.keywords,
"");l.length&&g.push(["kwd",new RegExpCompat("^(?:"+(new RegExpCompat("[\\s,]+","g"))[Symbol.replace](l,"|")+")\\b"),null]);c.push(["pln",new RegExpCompat("^\\s+"),null," \r\n\t\u00a0"]);l="^.[^\\s\\w.$@'\"`/\\\\]*";d.regexLiterals&&(l+="(?!s*/)");g.push(["lit",new RegExpCompat("^@[a-z_$][a-z_$@0-9]*","i"),null],["typ",new RegExpCompat("^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\\w+_t\\b)"),null],["pln",new RegExpCompat("^[a-z_$][a-z_$@0-9]*","i"),null],["lit",new RegExpCompat("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*",
"i"),null,"0123456789"],["pln",new RegExpCompat("^\\\\[\\s\\S]?"),null],["pun",new RegExpCompat(l),null]);return N(c,g)}function W(d,c,g){function l(a){var n=a.nodeType;if(1==n&&!G.test(a.className))if("br"===a.nodeName.toLowerCase())w(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)l(a);else if((3==n||4==n)&&g){var f=a.nodeValue,h=x[Symbol.match](f);h&&(n=f.substring(0,h.index),a.nodeValue=n,(f=f.substring(h.index+h[0].length))&&a.parentNode.insertBefore(t.createTextNode(f),
a.nextSibling),w(a),n||a.parentNode.removeChild(a))}}function w(a){function n(h,e){e=e?h.cloneNode(!1):h;var b=h.parentNode;if(b){b=n(b,1);h=h.nextSibling;b.appendChild(e);for(var k=h;k;k=h)h=k.nextSibling,b.appendChild(k)}return e}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;a=n(a.nextSibling,0);for(var f;(f=a.parentNode)&&1===f.nodeType;)a=f;m.push(a)}for(var G=new RegExpCompat("(?:^|\\s)nocode(?:\\s|$)"),x=new RegExpCompat("\\r\\n?|\\n"),t=d.ownerDocument,q=t.createElement("li");d.firstChild;)q.appendChild(d.firstChild);
for(var m=[q],p=0;p<m.length;++p)l(m[p]);c===(c|0)&&m[0].setAttribute("value",c);var z=t.createElement("ol");z.className="linenums";c=Math.max(0,c-1|0)||0;p=0;for(var y=m.length;p<y;++p)q=m[p],q.className="L"+(p+c)%10,q.firstChild||q.appendChild(t.createTextNode("\u00a0")),z.appendChild(q);d.appendChild(z)}function C(d,c){for(var g=c.length;0<=--g;){var l=c[g];X.hasOwnProperty(l)?S.console&&console.warn("cannot override language handler %s",l):X[l]=d}}function M(d,c){d&&X.hasOwnProperty(d)||(d=(new RegExpCompat("^\\s*<")).test(c)?
"default-markup":"default-code");return X[d]}function ka(d){var c=d.m;try{var g=D(d.j,d.o),l=g.g;d.g=l;d.h=g.h;d.l=0;M(c,l)(d);var w=(new RegExpCompat("\\bMSIE\\s(\\d+)")).exec(navigator.userAgent);w=w&&8>=+w[1];var G=new RegExpCompat("\n","g"),x=d.g,t=x.length;c=0;var q=d.h,m=q.length;g=0;var p=d.i,z=p.length;l=0;p[z]=t;var y,a;for(a=y=0;a<z;)p[a]!==p[a+2]?(p[y++]=p[a++],p[y++]=p[a++]):a+=2;z=y;for(a=y=0;a<z;){for(var n=p[a],f=p[a+1],h=a+2;h+2<=z&&p[h+1]===f;)h+=2;p[y++]=n;p[y++]=f;a=h}p.length=
y;var e=d.j;d="";e&&(d=e.style.display,e.style.display="none");try{for(;g<m;){var b=q[g+2]||t,k=p[l+2]||t;h=Math.min(b,k);var r=q[g+1],v;if(1!==r.nodeType&&(v=x.substring(c,h))){w&&(v=G[Symbol.replace](v,"\r"));r.nodeValue=v;var A=r.ownerDocument,B=A.createElement("span");B.className=p[l+1];var T=r.parentNode;T.replaceChild(B,r);B.appendChild(r);c<b&&(q[g+1]=r=A.createTextNode(x.substring(h,b)),T.insertBefore(r,B.nextSibling))}c=h;c>=b&&(g+=2);c>=k&&(l+=2)}}finally{e&&(e.style.display=d)}}catch(Y){S.console&&
console.log(Y&&Y.stack||Y)}}var S="undefined"!==typeof window?window:{},O=["break,continue,do,else,for,if,return,while"],P=[[O,"auto,case,char,const,default,double,enum,extern,float,goto,inline,int,long,register,restrict,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],U=[P,"alignas,alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,delegate,dynamic_cast,explicit,export,friend,generic,late_check,mutable,namespace,noexcept,noreturn,nullptr,property,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
la=[P,"abstract,assert,boolean,byte,extends,finally,final,implements,import,instanceof,interface,null,native,package,strictfp,super,synchronized,throws,transient"],ma=[P,"abstract,add,alias,as,ascending,async,await,base,bool,by,byte,checked,decimal,delegate,descending,dynamic,event,finally,fixed,foreach,from,get,global,group,implicit,in,interface,internal,into,is,join,let,lock,null,object,out,override,orderby,params,partial,readonly,ref,remove,sbyte,sealed,select,set,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,value,var,virtual,where,yield"];
P=[P,"abstract,async,await,constructor,debugger,enum,eval,export,from,function,get,import,implements,instanceof,interface,let,null,of,set,undefined,var,with,yield,Infinity,NaN"];var na=[O,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],oa=[O,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"];
O=[O,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"];var fa=[U,ma,la,P,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",na,oa,O],pa=new RegExpCompat("^(DIR|FILE|array|vector|(de|priority_)?queue|(forward_)?list|stack|(const_)?(reverse_)?iterator|(unordered_)?(multi)?(set|map)|bitset|u?(int|float)\\d*)\\b"),sa=new RegExpCompat("\\S");fa=F({keywords:fa,hashComments:!0,
cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0});var X={};C(fa,["default-code"]);C(N([],[["pln",new RegExpCompat("^[^<?]+")],["dec",new RegExpCompat("^<!\\w[^>]*(?:>|$)")],["com",new RegExpCompat("^<\\!--[\\s\\S]*?(?:-\\->|$)")],["lang-",new RegExpCompat("^<\\?([\\s\\S]+?)(?:\\?>|$)")],["lang-",new RegExpCompat("^<%([\\s\\S]+?)(?:%>|$)")],["pun",new RegExpCompat("^(?:<[%?]|[%?]>)")],["lang-",new RegExpCompat("^<xmp\\b[^>]*>([\\s\\S]+?)<\\/xmp\\b[^>]*>","i")],["lang-js",new RegExpCompat("^<script\\b[^>]*>([\\s\\S]*?)(<\\/script\\b[^>]*>)",
"i")],["lang-css",new RegExpCompat("^<style\\b[^>]*>([\\s\\S]*?)(<\\/style\\b[^>]*>)","i")],["lang-in.tag",new RegExpCompat("^(<\\/?[a-z][^<>]*>)","i")]]),"default-markup htm html mxml xhtml xml xsl".split(" "));C(N([["pln",new RegExpCompat("^[\\s]+"),null," \t\r\n"],["atv",new RegExpCompat("^(?:\\\"[^\\\"]*\\\"?|\\'[^\\']*\\'?)"),null,"\"'"]],[["tag",new RegExpCompat("^^<\\/?[a-z](?:[\\w.:-]*\\w)?|\\/?>$","i")],["atn",new RegExpCompat("^(?!style[\\s=]|on)[a-z](?:[\\w:-]*\\w)?","i")],["lang-uq.val",
new RegExpCompat("^=\\s*([^>\\'\\\"\\s]*(?:[^>\\'\\\"\\s\\/]|\\/(?=\\s)))")],["pun",new RegExpCompat("^[=<>\\/]+")],["lang-js",new RegExpCompat('^on\\w+\\s*=\\s*\\"([^\\"]+)\\"',"i")],["lang-js",new RegExpCompat("^on\\w+\\s*=\\s*\\'([^\\']+)\\'","i")],["lang-js",new RegExpCompat("^on\\w+\\s*=\\s*([^\\\"\\'>\\s]+)","i")],["lang-css",new RegExpCompat('^style\\s*=\\s*\\"([^\\"]+)\\"',"i")],["lang-css",new RegExpCompat("^style\\s*=\\s*\\'([^\\']+)\\'","i")],["lang-css",new RegExpCompat("^style\\s*=\\s*([^\\\"\\'>\\s]+)",
"i")]]),["in.tag"]);C(N([],[["atv",new RegExpCompat("^[\\s\\S]+")]]),["uq.val"]);C(F({keywords:U,hashComments:!0,cStyleComments:!0,types:pa}),"c cc cpp cxx cyc m".split(" "));C(F({keywords:"null,true,false"}),["json"]);C(F({keywords:ma,hashComments:!0,cStyleComments:!0,verbatimStrings:!0,types:pa}),["cs"]);C(F({keywords:la,cStyleComments:!0}),["java"]);C(F({keywords:O,hashComments:!0,multiLineStrings:!0}),["bash","bsh","csh","sh"]);C(F({keywords:na,hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),
["cv","py","python"]);C(F({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:!0,multiLineStrings:!0,regexLiterals:2}),["perl","pl","pm"]);C(F({keywords:oa,hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb","ruby"]);C(F({keywords:P,cStyleComments:!0,regexLiterals:!0}),["javascript","js","ts","typescript"]);C(F({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,throw,true,try,unless,until,when,while,yes",
hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);C(N([],[["str",new RegExpCompat("^[\\s\\S]+")]]),["regex"]);var va=S.PR={createSimpleLexer:N,registerLangHandler:C,sourceDecorator:F,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ",prettyPrintOne:function(d,c,g){g=
g||!1;c=c||null;var l=document.createElement("div");l.innerHTML="<pre>"+d+"</pre>";l=l.firstChild;g&&W(l,g,!0);ka({m:c,s:g,j:l,o:1,g:null,l:null,h:null,i:null});return l.innerHTML},prettyPrint:u=function(d,c){function g(){for(var e=S.PR_SHOULD_USE_CONTINUATION?q.now()+250:Infinity;m<w.length&&q.now()<e;m++){for(var b=w[m],k=h,r=b;r=r.previousSibling;){var v=r.nodeType,A=(7===v||8===v)&&r.nodeValue;if(A?!(new RegExpCompat("^\\??prettify\\b")).test(A):3!==v||(new RegExpCompat("\\S")).test(r.nodeValue))break;
if(A){k={};(new RegExpCompat("\\b(\\w+)=([\\w:.%+-]+)","g"))[Symbol.replace](A,function(Y,ta,ua){k[ta]=ua});break}}r=b.className;if((k!==h||z.test(r))&&!y.test(r)){v=!1;for(A=b.parentNode;A;A=A.parentNode){var B=A.tagName;if(B&&f.test(B)&&A.className&&z.test(A.className)){v=!0;break}}if(!v){b.className+=" prettyprinted";v=k.lang;if(!v){v=r.match(p);var T;!v&&(T=K(b))&&n.test(T.tagName)&&(v=p[Symbol.match](T.className));v&&=v[1]}a.test(b.tagName)?A=1:(A=b.currentStyle,B=l.defaultView,A=(A=A?A.whiteSpace:
B&&B.getComputedStyle?B.getComputedStyle(b,null).getPropertyValue("white-space"):0)&&"pre"===A.substring(0,3));B=k.linenums;(B="true"===B||+B)||(B=(B=(new RegExpCompat("\\blinenums\\b(?::(\\d+))?"))[Symbol.match](r))?B[1]&&B[1].length?+B[1]:!0:!1);B&&W(b,B,A);ka({m:v,j:b,s:B,o:A,g:null,l:null,h:null,i:null})}}}m<w.length?S.setTimeout(g,250):"function"===typeof d&&d()}c=c||document.body;var l=c.ownerDocument||document;c=[c.getElementsByTagName("pre"),c.getElementsByTagName("code"),c.getElementsByTagName("xmp")];
for(var w=[],G=0;G<c.length;++G)for(var x=0,t=c[G].length;x<t;++x)w.push(c[G][x]);c=null;var q=Date;q.now||(q={now:function(){return+new Date}});var m=0,p=new RegExpCompat("\\blang(?:uage)?-([\\w.]+)(?!\\S)"),z=new RegExpCompat("\\bprettyprint\\b"),y=new RegExpCompat("\\bprettyprinted\\b"),a=new RegExpCompat("pre|xmp","i"),n=new RegExpCompat("^code$","i"),f=new RegExpCompat("^(?:pre|code|xmp)$","i"),h={};g()}};U=S.define;"function"===typeof U&&U.amd&&U("google-code-prettify",[],function(){return va})})();
return u}();ea||J.setTimeout(ha,0)})();}()
